sorcery:
  google_callback_url: 'http://localhost:3000/oauth/callback?provider=google'
  line_callback_url: "https://localhost:9292/oauth/callback?provider=line"
default_url_options:
  host: "localhost:3000"